version: '3'
services:

 web:
  image: nginx
  volumes:
   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:   
   - "3888:80"
#  networks:
#   - net

 node1: 
  build: ./node1/
#  ports:
#   - "8888:80"
#  networks:
#   - net
 node2:
  build: ./node2/
#  ports:
#   - "8889:80"
#  networks:
#   - net

#networks:
#  net:

